const database = [
    {
        "name" : "Piccolo",
        "price" : "$29.99",
        "releaseNum" : 1,
        "releaseType" : "Retail Product",
        "releaseMonth" : "November",
        "releaseYear" : "2009",
        "region" : ["Japan"],
        "pagelink" : "001-piccolo.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/1172/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-piccolo-sh-figuarts-action-figure/ba59914"
    },
    {
        "name" : "Super Saiyan Son Goku",
        "price" : "$26.99",
        "releaseNum" : 2,
        "releaseType" : "Retail Product",
        "releaseMonth" : "January",
        "releaseYear" : "2010",
        "region" : ["Japan"],
        "pagelink" : "002-super-saiyan-son-goku.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/1216/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-super-saiyan-goku-sh-figuarts-action-figure/ba59912"
    },
    {
        "name" : "Super Saiyan Son Gohan",
        "price" : "$29.99",
        "releaseNum" : 3,
        "releaseType" : "Retail Product",
        "releaseMonth" : "July",
        "releaseYear" : "2010",
        "region" : ["Japan"],
        "pagelink" : "003-super-saiyan-son-gohan.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/1216/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-son-gohan-sh-figuarts-action-figure/ba61922"
    },
    {
        "name" : "Super Saiyan Son Goku (Special Color Edition)",
        "price" : "$35",
        "releaseNum" : 4,
        "releaseType" : "2011 SDCC Event Exclusive",
        "releaseMonth" : "July",
        "releaseYear" : "2011",
        "region" : ["USA"],
        "pagelink" : "004-super-saiyan-son-goku-event-2011.html",
        "tamashiiLink" : "Not Available",
        "eeLink" : "Not Available"
    },
    {
        "name" : "Super Saiyan Vegeta",
        "price" : "$39.99",
        "releaseNum" : 5,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "December",
        "releaseYear" : "2011",
        "region" : ["Japan"],
        "pagelink" : "005-super-saiyan-vegeta.html",
        "tamashiiLink" : "Not Available",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-super-saiyan-vegeta-sh-figuarts-figure/ba62466"
    },
    {
        "name" : "Trunks",
        "price" : "$48.99",
        "releaseNum" : 6,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "May",
        "releaseYear" : "2012",
        "region" : ["Japan"],
        "pagelink" : "006-trunks.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/11548/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-trunks-sh-figuarts-action-figure/ba73944"
    },
    {
        "name" : "Super Saiyan Son Gohan (Special Color Edition)",
        "price" : "$30",
        "releaseNum" : 7,
        "releaseType" : "2012 SDCC Event Exclusive",
        "releaseMonth" : "July",
        "releaseYear" : "2012",
        "region" : ["USA"],
        "pagelink" : "007-super-saiyan-son-gohan-event-2012.html",
        "tamashiiLink" : "Not Available",
        "eeLink" : "Not Available"
    },
    {
        "name" : "Perfect Cell",
        "price" : "$56.99",
        "releaseNum" : 8,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "November",
        "releaseYear" : "2012",
        "region" : ["Japan"],
        "pagelink" : "008-perfect-cell.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/10088/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragonball-z-perfect-cell-sh-figuarts-action-figure/ba73945?srsltid=AfmBOopmE5RFtd8vFEPaHJofYpQ3SNIVYPb0sOuNWMfyMz2Bn7GMMSGC"
    },
    {
        "name" : "Vegeta",
        "price" : "$47.99",
        "releaseNum" : 9,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "May",
        "releaseYear" : "2013",
        "region" : ["Japan"],
        "pagelink" : "009-vegeta.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/10221/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-seiyan-vegeta-sh-figuarts-action-figure/ba77459?srsltid=AfmBOoo4QX-X-KEKiXmAJvOjuxCmDAyNYdjs_NJpqL9l6x28lAP_WtRB"
    },
    {
        "name" : "Final Form Frieza",
        "price" : "$51.99",
        "releaseNum" : 10,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "July",
        "releaseYear" : "2013",
        "region" : ["Japan"],
        "pagelink" : "010-final-form-frieza.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/10271/?wovn=en",
        "eeLink" : ""
    },
    {
        "name" : "Piccolo (Special Color Edition)",
        "price" : "$40",
        "releaseNum" : 11,
        "releaseType" : "2013 SDCC Event Exclusive",
        "releaseMonth" : "July",
        "releaseYear" : "2013",
        "region" : ["USA"],
        "pagelink" : "011-piccolo-event-2013.html",
        "tamashiiLink" : "Not Available",
        "eeLink" : "Not Available"
    },
    {
        "name" : "Klilyn",
        "price" : "$39.99",
        "releaseNum" : 12,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "November",
        "releaseYear" : "2013",
        "region" : ["Japan"],
        "pagelink" : "012-klilyn.html",
        "tamashiiLink" : "https://tamashiiweb.com/item/10395/?wovn=en",
        "eeLink" : "https://www.entertainmentearth.com/product/dragon-ball-z-krillin-sh-figuarts-action-figure/ba80571?srsltid=AfmBOorH1ap02zFEnwkwphQXaBfweM0pHWlQ5xlHM7Uyc9krmZsyvHha",
    },
    {
        "name" : "Son Goku",
        "price" : "$40.99",
        "releaseNum" : 13,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "April",
        "releaseYear" : "2014",
        "region" : ["Japan"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashii.jp/item/10508/",
        "eeLink" : ""
    },
    {
        "name" : "Android 18",
        "price" : "$38.99",
        "releaseNum" : 14,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "June",
        "releaseYear" : "2014",
        "region" : ["Japan"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashiiweb.com/item/10595/?wovn=en",
        "eeLink" : ""
    },
    {
        "name" : "Vegeta (Original Animation Color Edition)",
        "price" : "$39.99",
        "releaseNum" : 15,
        "releaseType" : "2014 SDCC Event Exclusive",
        "releaseMonth" : "July",
        "releaseYear" : "2014",
        "region" : ["USA"],
        "pagelink" : "",
        "tamashiiLink" : "Not Available",
        "eeLink" : "Not Available"
    },
    {
        "name" : "Android 17",
        "price" : "$39.99",
        "releaseNum" : 16,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "October",
        "releaseYear" : "2014",
        "region" : ["Japan"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashiiweb.com/item/10656/?wovn=en",
        "eeLink" : ""
    },
    {
        "name" : "Broly",
        "price" : "$67.99",
        "releaseNum" : 17,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "November",
        "releaseYear" : "2014",
        "region" : ["Japan"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashiiweb.com/item/10744/?wovn=en",
        "eeLink" : ""
    },
    {
        "name" : "Android 16",
        "price" : "$61.99",
        "releaseNum" : 18,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "February",
        "releaseYear" : "2015",
        "region" : ["January"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashiiweb.com/item/10808/?wovn=en",
        "eeLink" : ""
    },
    {
        "name" : "Vegetto",
        "price" : "$39.99",
        "releaseNum" : 19,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "April",
        "releaseYear" : "2015",
        "region" : ["Japan"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashiiweb.com/item/10861/?wovn=en",
        "eeLink" : ""
    },
    {
        "name" : "Son Goku -for Galeria Tamashii Nations Mexico 2015-",
        "price" : "$45",
        "releaseNum" : 20,
        "releaseType" : "Galeria Tamashii Nations Mexico 2015",
        "releaseMonth" : "June",
        "releaseYear" : "2015",
        "region" : ["Mexico"],
        "pagelink" : "",
        "tamashiiLink" : "",
        "eeLink" : ""
    },
    {
        "name" : "Son Goku -Frieza Saga Ver.-",
        "price" : "$45",
        "releaseNum" : 21,
        "releaseType" : "2015 SDCC Event Exclusive",
        "releaseMonth" : "July",
        "releaseYear" : "2015",
        "region" : ["USA"],
        "pagelink" : "",
        "tamashiiLink" : "",
        "eeLink" : ""
    },
    {
        "name" : "Ultimate Son Gohan",
        "price" : "$35.99",
        "releaseNum" : 22,
        "releaseType" : "Premium Bandai",
        "releaseMonth" : "September",
        "releaseYear" : "2015",
        "region" : ["Japan"],
        "pagelink" : "",
        "tamashiiLink" : "https://tamashiiweb.com/item/11006/?wovn=en",
        "eeLink" : ""
    }
    /*
    {
        "name" : "",
        "price" : "$",
        "releaseNum" : ,
        "releaseType" : "",
        "releaseMonth" : "",
        "releaseYear" : "",
        "region" : [],
        "pagelink" : "",
        "tamashiiLink" : "",
        "eeLink" : ""
    }
    */
]